version: "3"
services:

  backend:
    build: .
    image: backend:latest
    depends_on: 
      - db
    ports:
      - "3000:3000"
    command: ["/main/wait-for-it.sh", "db:3306", "--", "npm", "run", "dev"]

  db:
    image: mysql:5.7
    volumes:
      - ./db-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: password


volumes:
  db-data: