version: "3"
services:

  backend:
    build: .
    image: backend:latest
    depends_on: 
      - db
    ports:
      - "3000:3000"
    command: ["/main/wait-for-it.sh", "db:3306", "--", "npm", "run", "dev"]

  db:
    image: mysql:5.7
    # volumes:
    #   - ./db-data:/var/lib/mysql
    ports:
      - "5000:3306"
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: root
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'


volumes:
  db-data: